#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"


echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[47;30m                       FERRAMENTAS                      \033[0m"
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
_PORTAS=$(lsof -V -i tcp -P -n | grep "LISTEN" | cut -d: -f2 | cut -d' ' -f1 | uniq)
for _PORTA in ${_PORTAS[@]}; do
printf '%-10s%-10s%-10s\n' "Porta: " "${_PORTA}" "Aberta"
done
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[01;34m\033[01;34m"
echo -e "|00| \033[01;34mVOLTAR AO MENU\033[01;34m"
echo -e "|01| \033[01;34mLIMPAR CACHE\033[01;34m"
echo -e "|02| \033[01;34mGERENCIADOR BACKUP DE USUARIOS\033[01;34m"
echo -e "|03| \033[01;34mBAD UDP\033[01;34m"
echo -e "|04| \033[01;34mTESTE DE CONEXAO\033[01;34m"
echo -e "|05| \033[01;34mUSO DE CPU, RAM e PROCESSOS DA MAQUINA\033[01;34m"
echo -e "|06| \033[01;34mCONFIGURAR SQUID 3\033[01;34m"
echo -e "|07| \033[01;34mCONFIGURAR OPENVPN\033[01;34m"
echo""
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[0;31m"
read -p "[00-05]: " opcao
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
case $opcao in
 00)
  PackSSH;;
  
 
 01)
  #limparCache.sh
#!/bin/bash

tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "Limpador e Swap" ; tput sgr0
echo ""

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/      //' > /etc/so
echo -e "\033[1;31mPARA LIMPAR O CACHE DE UM ENTER!\033[0m"
read -p "" ip


echo "Limpando o Cache e Swap..."
echo 3 > /proc/sys/vm/drop_caches
sysctl -w vm.drop_caches=3
swapoff -a && swapon -a
clear

service ssh restart & service squid3 restart
clear

echo -e "\033[01;31mLimpeza do Cache e Swap concluida\033[0m"

 02)
  tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "Gerenciador Backup de Usuários" ; tput sgr0
echo "O que deseja fazer?"
echo ""
echo "1 - CRIAR BACKUP"
echo "2 - RESTAURAR BACKUP"
echo "3 - SAIR"
echo ""

read -p "Opção: " -e -i 3 opcao

if [[ "$opcao" = '1' ]]; then
	if [ -f "/root/usuarios.db" ]
	then
		echo ""
		echo "Criando backup..."
		echo ""
		tar cvf /root/backup.vps /root/usuarios.db /etc/shadow /etc/passwd /etc/group /etc/gshadow
		echo ""
		echo "Arquivo /root/backup.vps criado com sucesso."
		echo ""
	else
		echo ""
		echo "Criando backup..."
		echo ""
		tar cvf /root/backup.vps /etc/shadow /etc/passwd /etc/group /etc/gshadow
		echo ""
		echo "Arquivo /root/backup.vps criado com sucesso."
		echo ""
	fi
fi
if [[ "$opcao" = '2' ]]; then
	if [ -f "/root/backup.vps" ]
	then
		echo ""
		echo "Restaurando backup..."
		echo ""
		sleep 1
		cp /root/backup.vps /backup.vps
		cd /
		tar -xvf backup.vps
		rm /backup.vps
		echo ""
		echo "Usuários e senhas importados com sucesso."
		echo ""
		exit
	else
		echo ""
		echo "O arquivo /root/backup.vps não foi encontrado!"
		echo "Ceritifique-se que ele esteja localizado no diretório /root/ com o nome backup.vps"
		echo ""
		exit
	fi
fi
  
esac
