#!/bin/bash

echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[47;30m                      FERRAMENTAS                       \033[0m"
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
_PORTAS=$(lsof -V -i tcp -P -n | grep "LISTEN" | cut -d: -f2 | cut -d' ' -f1 | uniq)
for _PORTA in ${_PORTAS[@]}; do
tput setaf 2 ; tput bold ; printf '%-10s%-10s%-10s\n' "Porta: " "${_PORTA}" "ON"
done
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[01;34m\033[01;34m"
echo -e "|00| \033[01;34mVOLTAR AO MENU\033[01;34m"
echo -e "|01| \033[01;34mLIMPAR CACHE\033[01;34m"
echo -e "|02| \033[01;34mGERENCIADOR BACKUP DE USUARIOS\033[01;34m"
echo -e "|03| \033[01;34mBAD UDP\033[01;34m"
echo -e "|04| \033[01;34mTESTE DE CONEXAO\033[01;34m"
echo -e "|05| \033[01;34mUSO DE CPU, RAM e PROCESSOS DA MAQUINA\033[01;34m"
echo -e "|06| \033[01;34mCONFIGURAR SQUID 3\033[01;34m"
echo -e "|07| \033[01;34mCONFIGURAR OPENVPN\033[01;34m"
echo""
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[0;31m"
read -p "[00-07]: " opcao
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
case $opcao in
00)
  PackSSH
  
esac
