#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"


echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[47;30m               GERENCIADOR DE USUARIOS                  \033[0m"
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
monitorar=$(ps x | grep "sshd:" | wc -l)
resultado=$(($monitorar-1))
echo -e "\033[0mTOTAL DE USUARIOS CONECTADOS:\033[1;31m $resultado \033[0m"
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[01;34m\033[01;34m"
echo -e "|00| \033[01;34mVOLTAR AO MENU\033[01;34m"
echo -e "|01| \033[01;34mCRIAR USUARIO SSH\033[01;34m"
echo -e "|02| \033[01;34mCRIAR USUARIO OPENVPN\033[01;34m"
echo -e "|03| \033[01;34mREMOVER USUARIO\033[01;34m"
echo -e "|04| \033[01;34mMUDAR VALIDADE DO USUARIO\033[01;34m"
echo -e "|05| \033[01;34mREMOVER USUARIO\033[01;34m"
echo -e "|06| \033[01;34mLIMITE DE CONEXAO POR USUARIO\033[01;34m"
echo -e "|07| \033[01;34mLIMPAR USUARIOS VENCIDOS\033[01;34m"
echo""
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[0;31m"
read -p "[00-07]: " opcao
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
case $opcao in
 00)
  PackSSH;;
  
 
 01)
  ClearCache
  sleep 1
  ferramentas;;
  
 02)
  UserBackup
  sleep 1
  ferramentas;;
