#!/bin/bash

clear
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;34m           ____            _     ____ ____  _   _                     \033[0m"
echo -e "\033[1;34m          |  _ \ __ _  ___| | __/ ___/ ___|| | | | Dev:   @MrCoppens  \033[0m" 
echo -e "\033[1;34m          | |_) / _  |/ __| |/ /\___ \___ \| |_| | CoDev: @Glemysson  \033[0m" 
echo -e "\033[1;34m          |  __/ (_| | (__|   <  ___) |__) |  _  |                    \033[0m" 
echo -e "\033[1;34m          |_|   \__,_|\___|_|\_\|____/____/|_| |_| V. 1.3 Beta        \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"

sleep 5

tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "INSTALANDO PACKSSH" ; tput sgr0


apt-get update &>/dev/null && echo -e '[=         ][10%] Progresso'
apt-get install bc &>/dev/null && echo -e '[==        ][20%] Progresso'
apt-get install nano &>/dev/null && echo -e '[===       ][30%] Progresso'
apt-get install htop &>/dev/null && echo -e '[====      ][40%] Progresso'
apt-get install python-pip -y &>/dev/null && echo -e '[=====     ][50%] Progresso'
pip install speedtest-cli &>/dev/null && echo -e '[======    ][60%] Progresso'
apt-get install nethogs -y &>/dev/null && echo -e '[=======   ][70%] Progresso'
apt-get install nload &>/dev/null && echo -e '[========  ][80%] Progresso'
iptables -F &>/dev/null && echo -e '[========= ][90%] Progresso'
apt-get install -y python3-pip &>/dev/null && echo -e '[==========][100%] Progresso'
sleep 2


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/TesteConexao -O /bin/SpeedTest
chmod +x /bin/SpeedTest

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/LimiterSSH -O /bin/LimiterSSH
chmod +x /bin/LimiterSSH

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/PackSSH -O /bin/PackSSH
chmod +x /bin/PackSSH

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/ferramentas -O /bin/ferramentas
chmod +x /bin/ferramentas

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/LimpadorCache -O /bin/ClearCache
chmod +x /bin/ClearCache

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/OpenUdp -O /bin/OpenUDP
chmod +x /bin/OpenUDP

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/UserBackup -O /bin/UserBackup
chmod +x /bin/UserBackup

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/Squid3 -O /bin/Squid3
chmod +x /bin/Squid3

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/OpenVPN -O /bin/OpenVPN
chmod +x /bin/OpenVPN

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/UserCreate -O /bin/UserCreate
chmod +x /bin/UserCreate

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/gerenciarusers -O /bin/gerenciarusers
chmod +x /bin/gerenciarusers

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/gerenciadorovpn -O /bin/gerenciadorovpn
chmod +x /bin/gerenciadorovpn

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/socks.py -O /bin/socks.py
chmod +x /bin/socks.py
clear




PackSSH
clear
