#!/bin/bash


echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;34m           ____            _     ____ ____  _   _                     \033[0m"
echo -e "\033[1;34m          |  _ \ __ _  ___| | __/ ___/ ___|| | | | Dev:   @MrCoppens  \033[0m" 
echo -e "\033[1;34m          | |_) / _  |/ __| |/ /\___ \___ \| |_| | CoDev: @Glemysson  \033[0m" 
echo -e "\033[1;34m          |  __/ (_| | (__|   <  ___) |__) |  _  |                    \033[0m" 
echo -e "\033[1;34m          |_|   \__,_|\___|_|\_\|____/____/|_| |_| V. 1.0             \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"

sleep 5

tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "INSTALANDO PACKSSH" ; tput sgr0
echo -e "\033[1;34m INSTALANDO...\033[1;32m"

apt-get update
apt-get install bc 
apt-get install nano
apt-get install htop
clear
apt-get install python-pip -y
pip install speedtest-cli
apt-get install nethogs -y
apt-get install nload
iptables -F
speep 1
apt-get update
apt-get install -y python3-pip


wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/TesteConexao -O /bin/SpeedTest
chmod +x /bin/SpeedTest

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/PackSSH -O /bin/PackSSH
chmod +x /bin/PackSSH

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/ferramentas -O /bin/ferramentas
chmod +x /bin/ferramentas

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/LimpadorCache -O /bin/ClearCache
chmod +x /bin/ClearCache

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/OpenUdp -O /bin/OpenUDP
chmod +x /bin/OpenUDP

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/UserBackup -O /bin/UserBackup
chmod +x /bin/UserBackup

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/Squid3 -O /bin/Squid3
chmod +x /bin/Squid3

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/OpenVPN -O /bin/OpenVPN
chmod +x /bin/OpenVPN

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/UserCreate -O /bin/UserCreate
chmod +x /bin/UserCreate


clear



echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[47;30m                    PACK SSH v1.0                       \033[0m"
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[47;30mDEVELOPER MRSSH e CO-DEVELOPER GLEYMISSON               \033[1;32m"
echo -e "\033[0mSISTEMA OPERACIONAL:\033[1;31m $(cat /etc/os-release | grep 'PRETTY_NAME' | cut -d= -f2 | sed 's/\"(*//g')\033[0m"
echo -e "\033[0mCPU:\033[1;31m $(cat /proc/cpuinfo | grep 'model name' | cut -d: -f2 | sed 's/ //')\033[0m"
echo -e "\033[0mRAM:\033[1;31m $(free -h | grep -i 'mem:' | awk -F' ' '{print $3"/"$2}')\033[0m" "\033[1;33m"{USADO/TOTAL}"\033[1;33m"
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[01;34m\033[01;34m"
echo -e "|01| \033[01;34mFERRAMENTAS\033[01;34m"
echo -e "|02| \033[01;34mGERENCIAR USUARIOS\033[01;34m"
echo""
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[0;31m"
read -p "[01-02]: " opcao
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
case $opcao in
 01)
  ferramentas
  sleep 1
 02
  gerenciarusers
  sleep 1

esac
