#!/bin/bash

clear
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;34m           ____            _     ____ ____  _   _                     \033[0m"
echo -e "\033[1;34m          |  _ \ __ _  ___| | __/ ___/ ___|| | | | Dev:   @MrCoppens  \033[0m" 
echo -e "\033[1;34m          | |_) / _  |/ __| |/ /\___ \___ \| |_| | CoDev: @Glemysson  \033[0m" 
echo -e "\033[1;34m          |  __/ (_| | (__|   <  ___) |__) |  _  |                    \033[0m" 
echo -e "\033[1;34m          |_|   \__,_|\___|_|\_\|____/____/|_| |_| V. 1.5 Beta        \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"

sleep 5

tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "INSTALANDO PACKSSH" ; tput sgr0
echo ""

apt-get update &>/dev/null && echo -e '[=         ][04%] Progresso'
apt-get install bc &>/dev/null && echo -e '[=         ][08%] Progresso'
apt-get install nano &>/dev/null && echo -e '[==        ][12%] Progresso'
apt-get install htop &>/dev/null && echo -e '[==        ][16%] Progresso'
apt-get install python-pip -y &>/dev/null && echo -e '[==        ][20%] Progresso'
pip install speedtest-cli &>/dev/null && echo -e '[===       ][24%] Progresso'
apt-get install nethogs -y &>/dev/null && echo -e '[===       ][28%] Progresso'
apt-get install nload &>/dev/null && echo -e '[====      ][32%] Progresso'
iptables -F &>/dev/null && echo -e '[====      ][36%] Progresso'
apt-get install -y python3-pip &>/dev/null && echo -e '[====      ][40%] Progresso'


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/TesteConexao -O /bin/SpeedTest &>/dev/null && echo -e '[=====     ][44%] Progresso'
chmod +x /bin/SpeedTest &>/dev/null  


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/LimiterSSH -O /bin/LimiterSSH &>/dev/null && echo -e '[=====     ][48%] Progresso'
chmod +x /bin/LimiterSSH &>/dev/null 


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/PackSSH -O /bin/PackSSH &>/dev/null && echo -e '[======    ][52%] Progresso'
chmod +x /bin/PackSSH &>/dev/null 


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/ferramentas -O /bin/ferramentas &>/dev/null && echo -e '[======    ][58%] Progresso'
chmod +x /bin/ferramentas &>/dev/null 


sleep 2
wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/LimpadorCache -O /bin/ClearCache &>/dev/null && echo -e '[=======   ][62%] Progresso'
chmod +x /bin/ClearCache &>/dev/null  


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/OpenUdp -O /bin/OpenUDP &>/dev/null && echo -e '[=======   ][66%] Progresso'
chmod +x /bin/OpenUDP &>/dev/null  


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/OpenInstallerNew -O /bin/OpenInstallerNew &>/dev/null && echo -e '[========  ][68%] Progresso'
chmod +x /bin/OpenInstallerNew &>/dev/null 


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/UserBackup -O /bin/UserBackup &>/dev/null && echo -e '[=======   ][70%] Progresso'
chmod +x /bin/UserBackup &>/dev/null 


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/Squid3 -O /bin/Squid3 &>/dev/null && echo -e '[========  ][74%] Progresso'
chmod +x /bin/Squid3 &>/dev/null  


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/OpenVPN -O /bin/OpenVPN &>/dev/null && echo -e '[========  ][78%] Progresso'
chmod +x /bin/OpenVPN &>/dev/null 


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/UserCreate -O /bin/UserCreate &>/dev/null && echo -e '[========= ][82%] Progresso'
chmod +x /bin/UserCreate &>/dev/null 

sleep 1

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/gerenciarusers -O /bin/gerenciarusers &>/dev/null && echo -e '[========= ][86%] Progresso'
chmod +x /bin/gerenciarusers &>/dev/null 


wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/gerenciadorovpn -O /bin/gerenciadorovpn &>/dev/null && echo -e '[==========][92%] Progresso'
chmod +x /bin/gerenciadorovpn &>/dev/null  

sleep 2

wget https://raw.githubusercontent.com/MrSSH/PackSSH/master/socks.py &>/dev/null && echo -e '[===========][100%] Progresso'

clear




PackSSH
clear
