#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

totalram=$(free | grep Mem | awk '{print $2}')
usedram=$(free | grep Mem | awk '{print $4}')
freeram=$(free | grep Mem | awk '{print $3}')
swapram=$( cat /proc/meminfo | grep SwapTotal | awk '{print $2}')

echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[47;30m                    PACK SSH v1.1 Beta                  \033[0m"
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[47;30mDEVELOPER MRSSH e CO-DEVELOPER GLEMYSSON                \033[0m"
echo -e "\033[0mSISTEMA OPERACIONAL:\033[1;31m $(cat /etc/os-release | grep 'PRETTY_NAME' | cut -d= -f2 | sed 's/\"(*//g')\033[0m"
echo -e "\033[0mCPU:\033[1;31m $(cat /proc/cpuinfo | grep 'model name' | cut -d: -f2 | sed 's/ //') x$(cat /proc/cpuinfo | grep processor | wc -l)\033[0m"
echo -e "\033[0mRAM:\033[1;31m TOTAL: $(($totalram / 1024))Mb\033[0m"
echo -e "\033[1;31m     USADO: $(($usedram / 1024))Mb\033[0m"
echo -e "\033[1;31m     LIVRE: $(($freeram / 1024))Mb\033[0m"
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[01;34m\033[01;34m"
echo -e "|01| \033[01;34mFERRAMENTAS\033[01;34m"
echo -e "|02| \033[01;34mGERENCIAR USUARIOS SSH\033[01;34m"
echo -e "|03| \033[01;34mGERENCIAR USUARIOS OPENVPN\033[01;34m"
echo""
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
echo -e "\033[0;31m"
read -p "[01-03]: " opcao
echo -e "\033[0;32m_________________________________________________________\033[0;32m"
case $opcao in
 01)
  ferramentas;;
 
  
 02)
  gerenciarusers;;
 
 
 03)
  gerenciadorovpn;;
esac
